SELECT HOSPITALIZATION.PF_CODE AS "都道府県コード", PF_NAME AS "都道府県名", ROUND(INP_YES * 100 / (INP_YES+INP_NO+UNIDENTIFIED), 1) AS "入院率"
FROM HOSPITALIZATION
INNER JOIN PREFECTURE
ON HOSPITALIZATION.PF_CODE = PREFECTURE.PF_CODE
-- PF_RATIO = (
--   ROUND((INP_YES * 100 / (INP_YES+INP_NO+UNIDENTIFIED)), -2)
-- )
-- ORDER BY PF_RATIO DESC, PF_CODE ASC
;
