SELECT POPU_TRANSITION.PF_CODE AS "都道府県コード", PREFECTURE.PF_NAME AS "都道府県名"
-- , "総人口2015年", "総人口2020年"
FROM POPU_TRANSITION
INNER JOIN PREFECTURE
ON POPU_TRANSITION.PF_CODE = PREFECTURE.PF_CODE
-- WHERE
--   (
--   SELECT POPU_TRANSITION.TOTAL_AMT
--   WHERE SURVEY_YEAR = 2020
--   )
--   - (
--   SELECT POPU_TRANSITION.TOTAL_AMT
--   WHERE SURVEY_YEAR = 2015
--   )
--   > 0
-- ORDER BY POPU_INC_RATIO DESC, PF_CODE ASC
;
