SELECT
  ITEM_POPULAR_RANK AS "RANK"
  , ITEM_CODE AS "CODE"
  , ITEM_NAME AS "NAME"
FROM ITEM
WHERE
  SALE_END_DATE IS NULL
  OR SALE_END_DATE > date("now")
ORDER BY
  ITEM_POPULAR_RANK ASC
  , ITEM_CODE ASC
;
