SELECT
  P.PF_CODE AS "CODE"
  , P.PF_NAME AS "NAME"
  , ROUND(CAST(S.PROMOTE_MUNICIPALITY AS REAL) / CAST(S.MUNICIPALITY_TTL AS REAL) * 100, 2) AS "RATIO"
FROM SDGS AS S
INNER JOIN PREFECTURE AS P
ON S.PF_CODE = P.PF_CODE
WHERE S.SURVEY_YEAR = 2022
ORDER BY
  "RATIO" DESC
  , P.PF_CODE ASC
;
