SELECT
  DST.DISTRICT_CODE AS "CODE"
  , DST.DISTRICT_NAME AS "NAME"
  , LCT.LATITUDE AS "LAT"
  , LCT.LONGITUDE AS "LON"
FROM LOCATION_TBL AS LCT
INNER JOIN DISTRICT AS DST
ON LCT.DISTRICT_CODE = DST.DISTRICT_CODE
WHERE DST.DISTRICT_CODE <> "1101"
ORDER BY
  (
    POW(ABS(LCT.LATITUDE - 43.044502), 2)
    + POW(ABS(LCT.LONGITUDE - 141.354139), 2)
  ) DESC
  , DST.DISTRICT_CODE ASC
;
